development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails-watch-list_development

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails-watch-list_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails-watch-list_production
